version: '3.8'
services:
  openclone-terraform:
    image: openclone-terraform:1.0
    container_name: openclone-terraform
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - "${OpenClone_Root_Dir}/OpenClone-Terraform:/workspaces/OpenClone-Terraform" # this just emulates what the devcontainer does when you don't use a docker-compose.yml
      - "${OpenClone_Root_Dir}/DatabaseRestore/:/DatabaseRestore"